---
name: ((deployment_name))

instance_groups:
- name: nexus-repo
  instances: 1
  vm_type: ((vm_type))
  persistent_disk_type: ((persistent_disk_type))
  stemcell: default
  azs: ((azs))
  networks:
  - name: default
  jobs:
  - name: nexus-repo
    release: nexus
    properties:
      nexus_repo:
        secrets:
          active_key: secret_1
          keys:
            secret_1: ((nexus_repo_encryption_secret_1))
        additional_nexus_vmoptions:
          - "-Dnexus.datastore.enabled=true"
          - "-Dnexus.datastore.nexus.username=((nexus_db_user))"
          - "-Dnexus.datastore.nexus.password=((nexus_db_password))"
          - "-Dnexus.datastore.nexus.jdbcUrl=((nexus_jdbc_url))"

variables:
  - name: nexus_repo_encryption_secret_1
    type: password
    options:
      length: 32

releases:
  - name: nexus
    version: ((nexus_version))

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: latest

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

