name: CI
on:
  push:
    branches:
    - actions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download BOSH CLI
      uses: docker://dpb587/gget
      with:
        args: github.com/cloudfoundry/bosh-cli "bosh=bosh-cli-*-linux-amd64"
    - name: Install BOSH CLI
      run: |
        set -ex
        mkdir -p  $GITHUB_WORKSPACE/bin
        sudo chmod +x ./bosh
        mv ./bosh $GITHUB_WORKSPACE/bin/
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        docker images
    - uses: docker://bosh/main-bosh-docker:latest
    - name: build
      env:
        FOO: 100
      run: |
        set -ex
        docker images