name: CI
on:
  push:
    branches:
    - actions
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Run tests against bosh on docker
      uses: s4heid/bosh-action@master
      with:
        script: ./ci/actions/test.sh